setw -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind | split-window -h
bind - split-window -v

set -g focus-events on
set -g extended-keys on
set -g extended-keys-format csi-u
